alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
global:
  evaluation_interval: 10s
  scrape_interval: 10s
rule_files:
- /etc/prometheus/rules/*.yaml
scrape_configs:
- job_name: cadvisor
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: alertmanager
  static_configs:
  - targets:
    - alertmanager:9093
- job_name: node_exporter
  static_configs:
  - targets:
    - node-exporter:9100
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: loki
  metrics_path: /metrics
  static_configs:
  - targets:
    - loki:3100
- job_name: promtail
  metrics_path: /metrics
  static_configs:
  - targets:
    - promtail:9080
