global:
  resolve_timeout: 5m
receivers:
- email_configs:
  - auth_password: YgVx28UQpfb0RNSL
    auth_username: ' 749398003@smtp-brevo.com'
    from: pwxcv7352@gmail.com
    smarthost: smtp-relay.brevo.com:587
    to: pwxcv7352@gmail.com
  name: email-notifications
route:
  group_by:
  - alertname
  group_interval: 5m
  group_wait: 30s
  receiver: email-notifications
  repeat_interval: 1h
